GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": " allra nyast"
}

###

PUT http://localhost:3001/todo/complete/6262cc1938f4a2661d8406e0

###

POST http://localhost:3001/users
Content-Type: application/json

{
    "user":
        {
            "username": "5",
            "password": "5"
        }
}

###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "user":
        {
            "username": "1",
            "password": "1"
        }
}

###

POST http://localhost:3001/auth/logout
Content-Type: application/json

{
    "user":
        {
            "username": "1",
            "password": "1"
        }
}
